project_name: docker-machine-driver-hetzner

builds:
  - id: docker-machine-driver-hetzner        # an internal name
    main: ./cmd/hetzner-driver # path to your package main
    binary: docker-machine-driver-hetzner     # what the produced binary will be called

    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
